[package]
name = "littlewing"
description = "A minimalist bitboard chess engine"
version = "0.4.0"
authors = ["Vincent Ollivier <v@vinc.cc>"]
repository = "https://github.com/vinc/littlewing"
homepage = "https://vinc.cc/projects/littlewing.html"
license = "GPL-3.0"

[lib]
name = "littlewing"
path = "src/lib.rs"

[[bin]]
name = "littlewing"
path = "src/main.rs"
doc = false

[dependencies]
getopts = "0.2"
lazy_static = "1.0"
rand = "0.4"
regex = "0.2"
rustyline = "1.0"
time = "0.1"

[badges]
travis-ci = { repository = "vinc/littlewing" }
